name: front_scaffold_flutter_v2
description: "This is a base project in Flutter designed as a template for future developments. It contains essential configurations and packages to quickly start new projects."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^4.2.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  go_router: ^14.8.1
  intl: any
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  image_picker: ^1.1.2
  formz: ^0.8.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/icon/
    - assets/fonts/
    - assets/images/
    - assets/app-icon/

  fonts:
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Light.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Medium.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-SemiBold.ttf
        - asset: assets/fonts/montserrat_alternates/MontserratAlternates-Bold.ttf

flutter_launcher_icons:
  # Configuration for the app icons on Android and iOS.

  # Path to the directory where the icon is located for Android.
  android: "launcher_icon"

  # Enables the creation of an icon for iOS.
  ios: true

  # Removes the alpha channel from the icon on iOS to avoid transparency issues.
  remove_alpha_ios: true

  # Path to the image that will be used as the main app icon.
  image_path: "assets/app-icon/app-icon.png"

  # Sets the background color of the adaptive icon on Android.
  adaptive_icon_background: "#254550"

  # Path to the image used as the foreground of the adaptive icon on Android.
  adaptive_icon_foreground: "assets/app-icon/app-icon-foreground.png"

  # Adjustment to slightly inset the adaptive icon foreground on Android.
  adaptive_icon_foreground_inset: 8

# flutter_native_splash: