name: front_scaffold_flutter_v2
description: "This is a base project in Flutter designed as a template for future developments. It contains essential configurations and packages to quickly start new projects."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.3.4
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  go_router: ^14.7.2
  intl: ^0.20.2
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_local_notifications: ^18.0.1
  image_picker: ^1.1.2
  formz: ^0.8.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true